name: Nix Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v24
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Build with Nix
      run: nix build

    - name: Test binary exists
      run: test -f result/bin/geekymenu

    - name: Check flake
      run: nix flake check

    - name: Test development shell
      run: nix develop --command bash -c 'node --version && npm --version'
